name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: ./test_unishox3 -t && ./test_unishox3-w-olen -t
    - name: test sample_texts/chinese.txt
      run: ./test_unishox3 -c sample_texts/chinese.txt sample_texts/chinese.usx && ./test_unishox3 -d sample_texts/chinese.usx sample_texts/chinese.dsx && cmp sample_texts/chinese.txt sample_texts/chinese.dsx
    - name: test sample_texts/emoji.txt
      run: ./test_unishox3 -c sample_texts/emoji.txt sample_texts/emoji.usx && ./test_unishox3 -d sample_texts/emoji.usx sample_texts/emoji.dsx && cmp sample_texts/emoji.txt sample_texts/emoji.dsx
    - name: test sample_texts/french.txt
      run: ./test_unishox3 -c sample_texts/french.txt sample_texts/french.usx && ./test_unishox3 -d sample_texts/french.usx sample_texts/french.dsx && cmp sample_texts/french.txt sample_texts/french.dsx
    - name: test sample_texts/hindi.txt
      run: ./test_unishox3 -c sample_texts/hindi.txt sample_texts/hindi.usx && ./test_unishox3 -d sample_texts/hindi.usx sample_texts/hindi.dsx && cmp sample_texts/hindi.txt sample_texts/hindi.dsx
    - name: test sample_texts/japanese.txt
      run: ./test_unishox3 -c sample_texts/japanese.txt sample_texts/japanese.usx && ./test_unishox3 -d sample_texts/japanese.usx sample_texts/japanese.dsx && cmp sample_texts/japanese.txt sample_texts/japanese.dsx
    - name: test sample_texts/json1.txt
      run: ./test_unishox3 -c sample_texts/json1.txt sample_texts/json1.usx && ./test_unishox3 -d sample_texts/json1.usx sample_texts/json1.dsx && cmp sample_texts/json1.txt sample_texts/json1.dsx
    - name: test sample_texts/json2.txt
      run: ./test_unishox3 -c sample_texts/json2.txt sample_texts/json2.usx && ./test_unishox3 -d sample_texts/json2.usx sample_texts/json2.dsx && cmp sample_texts/json2.txt sample_texts/json2.dsx
    - name: test sample_texts/json3.txt
      run: ./test_unishox3 -c sample_texts/json3.txt sample_texts/json3.usx && ./test_unishox3 -d sample_texts/json3.usx sample_texts/json3.dsx && cmp sample_texts/json3.txt sample_texts/json3.dsx
    - name: test sample_texts/json4.txt
      run: ./test_unishox3 -c sample_texts/json4.txt sample_texts/json4.usx && ./test_unishox3 -d sample_texts/json4.usx sample_texts/json4.dsx && cmp sample_texts/json4.txt sample_texts/json4.dsx
    - name: test sample_texts/korean.txt
      run: ./test_unishox3 -c sample_texts/korean.txt sample_texts/korean.usx && ./test_unishox3 -d sample_texts/korean.usx sample_texts/korean.dsx && cmp sample_texts/korean.txt sample_texts/korean.dsx
    - name: test sample_texts/spanish.txt
      run: ./test_unishox3 -c sample_texts/spanish.txt sample_texts/spanish.usx && ./test_unishox3 -d sample_texts/spanish.usx sample_texts/spanish.dsx && cmp sample_texts/spanish.txt sample_texts/spanish.dsx
    - name: test sample_texts/tamil.txt
      run: ./test_unishox3 -c sample_texts/tamil.txt sample_texts/tamil.usx && ./test_unishox3 -d sample_texts/tamil.usx sample_texts/tamil.dsx && cmp sample_texts/tamil.txt sample_texts/tamil.dsx
    - name: test sample_texts/xml1.txt
      run: ./test_unishox3 -c sample_texts/xml1.txt sample_texts/xml1.usx && ./test_unishox3 -d sample_texts/xml1.usx sample_texts/xml1.dsx && cmp sample_texts/xml1.txt sample_texts/xml1.dsx
    - name: test sample_texts/world95.txt
      run: ./test_unishox3 -c sample_texts/world95.txt sample_texts/world95.usx && ./test_unishox3 -d sample_texts/world95.usx sample_texts/world95.dsx && cmp sample_texts/world95.txt sample_texts/world95.dsx
    - name: test sample_texts/alice_wland_chn.txt
      run: ./test_unishox3 -c sample_texts/alice_wland_chn.txt sample_texts/alice_wland_chn.usx && ./test_unishox3 -d sample_texts/alice_wland_chn.usx sample_texts/alice_wland_chn.dsx && cmp sample_texts/alice_wland_chn.txt sample_texts/alice_wland_chn.dsx
    - name: test sample_texts/alice_wland.txt
      run: ./test_unishox3 -c sample_texts/alice_wland.txt sample_texts/alice_wland.usx && ./test_unishox3 -d sample_texts/alice_wland.usx sample_texts/alice_wland.dsx && cmp sample_texts/alice_wland.txt sample_texts/alice_wland.dsx
    - name: test sample_texts/hi.txt
      run: ./test_unishox3 -c sample_texts/hi.txt sample_texts/hi.usx && ./test_unishox3 -d sample_texts/hi.usx sample_texts/hi.dsx && cmp sample_texts/hi.txt sample_texts/hi.dsx
    - name: test sample_texts/ja.txt
      run: ./test_unishox3 -c sample_texts/ja.txt sample_texts/ja.usx && ./test_unishox3 -d sample_texts/ja.usx sample_texts/ja.dsx && cmp sample_texts/ja.txt sample_texts/ja.dsx
    - name: test sample_texts/ru.txt
      run: ./test_unishox3 -c sample_texts/ru.txt sample_texts/ru.usx && ./test_unishox3 -d sample_texts/ru.usx sample_texts/ru.dsx && cmp sample_texts/ru.txt sample_texts/ru.dsx
    - name: test sample_texts/ta.txt
      run: ./test_unishox3 -c sample_texts/ta.txt sample_texts/ta.usx && ./test_unishox3 -d sample_texts/ta.usx sample_texts/ta.dsx && cmp sample_texts/ta.txt sample_texts/ta.dsx
    - name: test sample_texts/zh.txt
      run: ./test_unishox3 -c sample_texts/zh.txt sample_texts/zh.usx && ./test_unishox3 -d sample_texts/zh.usx sample_texts/zh.dsx && cmp sample_texts/zh.txt sample_texts/zh.dsx
